### ISSUE TITLE
mkdocs 配置示例

### ISSUE THREAD

**Issue by hyoban** [hyoban/hyoban.github.io#15]
```yml
site_name: Hyoban's Note
site_url: https://note.hyoban.fun

theme:
  name: material
  favicon: assets/images/favicon.ico
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.expand

markdown_extensions:
  # markdown highlight
  - pymdownx.highlight
  - pymdownx.superfences
  # add HTML attributes and CSS classes to Markdown elements
  - attr_list
  # 修改 toc 链接为具体标题
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
  # 提供下划线，删除线的支持
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - Home: index.md
  - XX:
    - xx: xx.md

```
